### NumPy 불러오기

In [2]:
import numpy as np

### 배열 생성하기

리스트를 배열로 변환

In [2]:
arr1 = np.array([1, 2, 3])
arr1

array([1, 2, 3])

In [5]:
print(type(arr1))

<class 'numpy.ndarray'>


함수로 배열 생성하기

In [4]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr1 = np.zeros((2,2)) # 모든 값이 0인 배열 생성
arr1

array([[ 0.,  0.],
       [ 0.,  0.]])

In [4]:
arr2 = np.ones((1,2)) # 모든 값이 1인 배열 생성
arr2

array([[ 1.,  1.]])

In [6]:
arr3 = np.full((1,2), 10) # 모든 값이 특정 상수인 배열 생성
arr3

C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\numeric.py:301: FutureWarning: in the future, full((1, 2), 10) will return an array of dtype('int32')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


array([[ 10.,  10.]])

In [8]:
arr4 = np.eye(3) # 단위행렬 생성
arr4

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [9]:
arr5 = np.random.random((2,2)) # 랜덤한 값으로 채워진 배열 생성
arr5

array([[ 0.43185899,  0.10813613],
       [ 0.85616989,  0.78237002]])

### 배열의 rank와 shape

In [8]:
arr1 = np.array([1, 2, 3])
print(arr1.ndim)
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2.ndim)
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3.ndim)

1
2
3


In [9]:
arr1 = np.array([1, 2, 3])
print(arr1.shape)
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2.shape)
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3.shape)

(3,)
(2, 3)
(2, 2, 3)


### 배열 인덱싱하기

In [10]:
arr1 = np.array([1, 2, 3])
arr1[0]

1

In [11]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2[1]

array([4, 5, 6])

In [12]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3[0][1]

array([4, 5, 6])

In [13]:
arr3[0,0,1]

2

In [14]:
arr4 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr5 = arr4[:2, :]
arr5

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

불리언 인덱싱(Boolean indexing)

In [15]:
arr1 = np.array([[1,2], [3, 4], [5, 6]])
idx = (arr1 > 3)
idx

array([[False, False],
       [False,  True],
       [ True,  True]], dtype=bool)

In [16]:
arr1[idx]

array([4, 5, 6])

### 배열 자료형

In [18]:
arr1 = np.array([1])
arr1.dtype

dtype('int32')

In [19]:
arr2 = np.array([1.0])
arr2.dtype

dtype('float64')

In [20]:
arr3 = np.array([1,2], dtype = np.float64)
arr3.dtype

dtype('float64')

### 배열 연산

기초연산

In [21]:
arr1 = np.array([[1,2], [3,4]], dtype = np.float64)
arr2 = np.array([[5,6], [7,8]], dtype = np.float64)

In [22]:
arr1 + arr2

array([[  6.,   8.],
       [ 10.,  12.]])

In [23]:
arr1 - arr2

array([[-4., -4.],
       [-4., -4.]])

In [24]:
# 행렬의 곱연산이 아님 
arr1 * arr2

array([[  5.,  12.],
       [ 21.,  32.]])

In [25]:
arr1 / arr2

array([[ 0.2       ,  0.33333333],
       [ 0.42857143,  0.5       ]])

np.sqrt(arr1)

내적 및 행렬의 곱연산

In [27]:
# 백터의 내적
vector1 = np.array([1,2])
vector2 = np.array([3,4])
np.dot(vector1, vector2)

11

In [28]:
# 행렬의 곱연산
arr1 = np.array([[1,2], [3,4]], dtype = np.float64)
arr2 = np.array([[5,6], [7,8]], dtype = np.float64)
np.dot(arr1, arr2)

array([[ 19.,  22.],
       [ 43.,  50.]])

sum 연산

In [29]:
arr1 = np.array([[1,2], [3,4]], dtype = np.float64)
np.sum(arr1)

10.0

In [31]:
np.sum(arr1, axis = 0)

array([ 4.,  6.])

In [32]:
np.sum(arr1, axis = 1)

array([ 3.,  7.])

전치행렬

In [33]:
arr1 = np.array([[1,2], [3,4]], dtype = np.float64)
arr1

array([[ 1.,  2.],
       [ 3.,  4.]])

In [34]:
arr1.T # 행과 열을 바꿈

array([[ 1.,  3.],
       [ 2.,  4.]])